# Development Environment Configuration
spring.application.name=dominator-dev

# Postgre SQL - Connection
spring.datasource.url=${POSTGRE_SQL_URI}
spring.datasource.username=${POSTGRE_SQL_USER}
spring.datasource.password=${POSTGRE_SQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 20 min
# 10 min
# 5 min
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000
# Mantener vivas las conexiones
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration - Production
server.port=${SERVER_PORT_BACK:8082}

# Security Configuration - Production
jwt-secret=${JWT_SECRET}

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=1KB

# Upload Directory Configuration
app.upload.dir=uploads/images


minio.url=${MINIO_ENDPOINT:http://localhost:9000}
minio.access.key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret.key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket.name=${MINIO_BUCKET_NAME:name-bucket}

# Client Dipomex
client.dipomex.base-url=${CLIENT_DIPOMEX_URL}/v1
client.dipomex.token=${CLIENT_DIPOMEX_TOKEN}
