# ==========================================
# DEVELOPMENT CONFIGURATION
# ==========================================
spring.application.title=Gestor API - Development

# ----------------------------------------
# DATABASE CONNECTION (Dev overrides)
# ----------------------------------------
spring.datasource.url=${POSTGRE_SQL_URI}
spring.datasource.username=${POSTGRE_SQL_USER}
spring.datasource.password=${POSTGRE_SQL_PASSWORD}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------
# SERVER
# ----------------------------------------
server.port=${SERVER_PORT_BACK:8082}

# ----------------------------------------
# SECURITY
# ----------------------------------------
jwt-secret=${JWT_SECRET}

# ----------------------------------------
# MINIO (Dev defaults)
# ----------------------------------------
minio.url=${MINIO_ENDPOINT:http://localhost:9000}
minio.access.key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret.key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket.name=${MINIO_BUCKET_NAME:name-bucket}
