# ==========================================
# PRODUCTION CONFIGURATION
# ==========================================
spring.application.title=Gestor API - Production

# ----------------------------------------
# SERVER
# ----------------------------------------
server.port=${SERVER_PORT_BACK:8082}

# HikariCP specific for Prod (Performance tuning)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# JPA / HIBERNATE (Strictly NONE in prod to avoid accidental dropping)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=validate

# ----------------------------------------
# LOGGING (Clean logs for prod)
# ----------------------------------------
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF

# ----------------------------------------
# MINIO (Strictly Env variables, no fallbacks)
# ----------------------------------------
minio.url=${MINIO_ENDPOINT}
minio.access.key=${MINIO_ACCESS_KEY}
minio.secret.key=${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}
