# ==========================================
# BASE CONFIGURATION (Common to all profiles)
# ==========================================

spring.application.name=dominator
spring.application.version=0.0.1

# Default active profile (can be overridden via env var SPRING_PROFILES_ACTIVE)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# ----------------------------------------
# FILE UPLOAD CONFIGURATION
# ----------------------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=1KB

# Upload Directory Configuration
app.upload.dir=uploads/images

# ----------------------------------------
# DATABASE CONNECTION (Drivers and Base Hikari)
# ----------------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true

# ----------------------------------------
# CLIENT DIPOMEX
# ----------------------------------------
client.dipomex.base-url=${CLIENT_DIPOMEX_URL}/v1
client.dipomex.token=${CLIENT_DIPOMEX_TOKEN}
