# ==========================================
# BASE CONFIGURATION (Common to all profiles)
# ==========================================
spring.application.name=gestor-api
spring.application.version=0.0.1

# ----------------------------------------
# FILE UPLOAD CONFIGURATION
# ----------------------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=1KB

# ----------------------------------------
# DATABASE CONNECTION (Dev overrides)
# ----------------------------------------
spring.datasource.url=${POSTGRE_SQL_URI}
spring.datasource.username=${POSTGRE_SQL_USER}
spring.datasource.password=${POSTGRE_SQL_PASSWORD}

# ----------------------------------------
# DATABASE CONNECTION (Drivers and Base Hikari)
# ----------------------------------------
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true

# ----------------------------------------
# SECURITY & CORS
# ----------------------------------------
jwt-secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}
app.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}

# ----------------------------------------
# CLIENT DIPOMEX
# ----------------------------------------
client.dipomex.base-url=${CLIENT_DIPOMEX_URL}/v1
client.dipomex.token=${CLIENT_DIPOMEX_TOKEN}